### PR TITLE
unified code generation

### PR DESCRIPTION
**Pull request by c-cube**
add -unified, to emit all code into a single module for each .proto

### CODE REVIEW

**Comment by Lupus** [comment]
@c-cube is this something that can help in compiling a bunch of proto files from some complex hierarchy where some of the files have the same names potentially (like `foo/v1/api.proto` and `bar/v2/api.proto`)?

**Comment by c-cube** [comment]
That's the hope, it does need testing in the situation with multiple files. It also simplifies dune rules because you have fewer targets.

**Comment by Lupus** [comment]
Hm, but that is likely to complicate the generation for someone, using the compiler library? I'm already generating additional files for client/service stubs. Also I'm currently prototyping some validation code and wanted to start with producing some other files with validation code and a bit modified types (no options for required message fields, some Time.t for timestamps etc).

**Comment by c-cube** [comment]
To be honest, if I could rewrite history I'd always generate just one module per .proto file. If you look at the change, most of the codegen is the same (although it might need more changes when referring to other modules), it's the glue part at the cli level that is affected.

**Comment by Lupus** [comment]
Yeah, changes seem to mostly be localized at the cli level indeed. Maybe cli could also be moved to some library part to be reused in other cli drivers 🤔 I need to look into what parts I fork and do I really need to fork them...

Btw, should `module_name_of_proto_file_name` take package into the account instead of relying on filenames?

**Comment by c-cube** [comment]
On August 21, 2023 8:09:50 AM EDT, "Konstantin A. Olkhovskiy" ***@***.***> wrote:
>Yeah, changes seem to mostly be localized at the cli level indeed. Maybe cli could also be moved to some library part to be reused in other cli drivers 🤔 

Yes indeed. I think additional code generators could be sort of plug-ins (take the ocaml ast and two output streams, writes the generated code into the streams). The code already looks like that. A library would help for sure. 



>Btw, should `module_name_of_proto_file_name` take package into the account instead of relying on filenames?

I think ocaml-protoc ignores that? The new function follows what the existing code to find the file name does, and file name implies module name.

**Comment by Lupus** [comment]
>  I think additional code generators could be sort of plug-ins

Sounds great!

> I think ocaml-protoc ignores that? The new function follows what the existing code to find the file name does, and file name implies module name.

Yeah, currently it's ignored, which does not help with large industrial collections of protobufs, IDL monorepo style. But this seems separate from what this PR is introducing, so probably better discuss this elsewhere after this PR gets landed.

**Pull request closed without merging**
