### PR TITLE
nested write by cached buffers

### PR DESCRIPTION
**Pull request by c-cube**
benchmarks seem to indicate that this works well. It's also very straightforward and does not require modifications to the generated code.

cc @vphantom to try it out if you so wish :)

It also exposes a `write_chunks` function to be able to output slice(s) using any IO function (currently only one chunk but who knows).

### CODE REVIEW

**Comment by mransan** [comment]
Looks good, are you able to run the integration test. (those tests run against the google C++ implementation and are generally the best indicator that everything is Ok).

**Comment by c-cube** [comment]
I didn't realize they were included. I tried:

```
$ make integration
make: /usr/local/bin/protoc: No such file or directory
```

**Comment by c-cube** [comment]
Oh god, seems like protoc generates code that doesn't compile?  Is `test14.pb.h` generated by protoc itself?

Line 134 of `test14.pb.h` is:

```c++
  friend void swap(a& a, a& b) {
    a.Swap(&b);
  }
```

but this _fails_ with g++.  The fix is:

```c++
  friend void swap(a& a, class a& b) {
    a.Swap(&b);
  }
```

probably because `a`, in context, is both a type and an object?

**Comment by c-cube** [comment]
but otherwise I ran the integration tests with errcode=0, I suppose it means it works?

**Comment by mransan** [comment]
You mean everything but test14 works? If so yes it should be ok. I think the fix might be the G++ version or some command line argument.

**Comment by c-cube** [comment]
> You mean everything but test14 works? If so yes it should be ok. I think the fix might be the G++ version or some command line argument.

I should have been more clear. Everything passes including test14, after fixing the line in the generated C++. I was just checking that the return code is the right way of checking that it works :)

**Pull request merged**
