### PR TITLE
Parsing of Pb_options according to protobuf schema

### PR DESCRIPTION
**Pull request by Lupus**

### CODE REVIEW

**Comment by Lupus** [comment]
@c-cube could you please take a look? This is required for further upstreaming of validation generator.

**Comment by c-cube** [comment]
I can look, but I've also been slowly trying to fix integration tests on master (which were silently broken).  Would you look at #243 in the mean time?

**Comment by c-cube** [comment]
Right now, on my branch (and on this rebased on my branch) `dune build src/tests/integration-tests/test_make.ml` fails, and I bisected it back to either:
- 8c3dbd54081f7ecb5a842f8aba50968b228f3010
- b1002fe478eaf2828ce181ce28554aa2523dec5c

which might have broken packed repeated fields? :/

**Comment by Lupus** [comment]
> Right now, on my branch (and on this rebased on my branch) `dune build src/tests/integration-tests/test_make.ml` fails, and I bisected it back to either:
> 
> * [8c3dbd5](https://github.com/mransan/ocaml-protoc/commit/8c3dbd54081f7ecb5a842f8aba50968b228f3010)
> * [b1002fe](https://github.com/mransan/ocaml-protoc/commit/b1002fe478eaf2828ce181ce28554aa2523dec5c)
> 
> which might have broken packed repeated fields? :/

Yeah, something is wrong, I've got a repro, looking into this.

**Comment by c-cube** [comment]
merged #243 which conflicts with this, but we're close, I think :).

**Comment by Lupus** [comment]
Okay, I think I fixed it. This PR includes a small unrelated commit that forces compilation of `option_processing.proto`, and a fix to duplicate `id` fields in that file... I hope it's fine to have this extra commit on this PR :)

**Comment by c-cube** [comment]
It's great! Look at that, it even passes integration tests :grin: .

**Pull request merged**
