### PR TITLE
Support code generation for empty messages

### PR DESCRIPTION
**Pull request by Lupus**
This PR introduces generation of code for empty messages. Currently it's not possible to serialize/deserialize empty message directly, as it's just omitted from code generation.

### CODE REVIEW

**Comment by c-cube** [comment]
This looks very useful! Can we get a unit test (which are easier to run than integration tests) as well?

**Comment by Lupus** [comment]
I'll look into adding one.

**Comment by Lupus** [comment]
@c-cube any pointers on where should this test reside and what kind of test do you think would make sense? 🤔 
I've quickly glanced through the files with unit tests and didn't find a suitable spot right away...

**Comment by c-cube** [comment]
the integration test will do for now, thanks :)

**Comment by Lupus** [comment]
Cool, thanks for quick turnaround!

**Pull request merged**
