### PR TITLE
performance-related changes

### PR DESCRIPTION
**Pull request by c-cube**
this now needs benchmarks for the new varint implementations (I only looked at the asm). Otherwise the bytes-related stuff is clearly a win :)

### CODE REVIEW

**Comment by c-cube** [comment]
I wrote benchmarks (in `benchs/benchs.ml`).
On my machine (Intel i7-7500, 2.70GHz), I get:

```
*** Run benchmarks for path "varint.dec.dec 10"

Throughputs for "dec-varint-imp", "dec-varint-rec" each running for at least 4 CPU seconds:
dec-varint-imp:  4.63 WALL ( 4.60 usr +  0.00 sys =  4.60 CPU) @ 16047931.69/s (n=73879815)
dec-varint-rec:  4.76 WALL ( 4.73 usr +  0.00 sys =  4.73 CPU) @ 13554950.84/s (n=64100129)
                     Rate dec-varint-rec dec-varint-imp
dec-varint-rec 13554951/s             --           -16%
dec-varint-imp 16047932/s            18%             --
**********************************************************************
*** Run benchmarks for path "varint.dec.dec 1000"

Throughputs for "dec-varint-imp", "dec-varint-rec" each running for at least 4 CPU seconds:
dec-varint-imp:  4.49 WALL ( 4.46 usr +  0.00 sys =  4.46 CPU) @ 115531.72/s (n=515457)
dec-varint-rec:  4.16 WALL ( 4.15 usr +  0.00 sys =  4.15 CPU) @ 91616.16/s (n=379785)
                   Rate dec-varint-rec dec-varint-imp
dec-varint-rec  91616/s             --           -21%
dec-varint-imp 115532/s            26%             --
**********************************************************************
*** Run benchmarks for path "varint.dec.dec 5"

Throughputs for "dec-varint-imp", "dec-varint-rec" each running for at least 4 CPU seconds:
dec-varint-imp:  4.21 WALL ( 4.20 usr +  0.00 sys =  4.20 CPU) @ 31007344.48/s (n=130299156)
dec-varint-rec:  4.21 WALL ( 4.20 usr +  0.00 sys =  4.20 CPU) @ 25397185.54/s (n=106695786)
                     Rate dec-varint-rec dec-varint-imp
dec-varint-rec 25397186/s             --           -18%
dec-varint-imp 31007344/s            22%             --
**********************************************************************
*** Run benchmarks for path "varint.dec.dec 50"

Throughputs for "dec-varint-imp", "dec-varint-rec" each running for at least 4 CPU seconds:
dec-varint-imp:  4.42 WALL ( 4.42 usr +  0.00 sys =  4.42 CPU) @ 3657329.37/s (n=16164679)
dec-varint-rec:  4.80 WALL ( 4.65 usr +  0.01 sys =  4.66 CPU) @ 2242315.91/s (n=10446248)
                    Rate dec-varint-rec dec-varint-imp
dec-varint-rec 2242316/s             --           -39%
dec-varint-imp 3657329/s            63%             --
**********************************************************************
*** Run benchmarks for path "varint.enc.enc 10"

Throughputs for "enc-varint-imp", "enc-varint-rec" each running for at least 4 CPU seconds:
enc-varint-imp:  4.08 WALL ( 4.06 usr +  0.00 sys =  4.06 CPU) @ 16285390.01/s (n=66161514)
enc-varint-rec:  4.61 WALL ( 4.53 usr +  0.01 sys =  4.53 CPU) @ 7427259.31/s (n=33680831)
                     Rate enc-varint-rec enc-varint-imp
enc-varint-rec  7427259/s             --           -54%
enc-varint-imp 16285390/s           119%             --
**********************************************************************
*** Run benchmarks for path "varint.enc.enc 1000"

Throughputs for "enc-varint-imp", "enc-varint-rec" each running for at least 4 CPU seconds:
enc-varint-imp:  4.56 WALL ( 4.50 usr +  0.00 sys =  4.50 CPU) @ 105631.92/s (n=475365)
enc-varint-rec:  4.10 WALL ( 4.06 usr +  0.01 sys =  4.07 CPU) @ 62512.87/s (n=254308)
                   Rate enc-varint-rec enc-varint-imp
enc-varint-rec  62513/s             --           -41%
enc-varint-imp 105632/s            69%             --
**********************************************************************
*** Run benchmarks for path "varint.enc.enc 5"

Throughputs for "enc-varint-imp", "enc-varint-rec" each running for at least 4 CPU seconds:
enc-varint-imp:  4.27 WALL ( 4.26 usr +  0.00 sys =  4.26 CPU) @ 32906337.54/s (n=140030945)
enc-varint-rec:  4.17 WALL ( 4.15 usr +  0.00 sys =  4.15 CPU) @ 20838012.71/s (n=86394234)
                     Rate enc-varint-rec enc-varint-imp
enc-varint-rec 20838013/s             --           -37%
enc-varint-imp 32906338/s            58%             --
**********************************************************************
*** Run benchmarks for path "varint.enc.enc 50"

Throughputs for "enc-varint-imp", "enc-varint-rec" each running for at least 4 CPU seconds:
enc-varint-imp:  4.74 WALL ( 4.67 usr +  0.01 sys =  4.68 CPU) @ 3692143.08/s (n=17284262)
enc-varint-rec:  4.17 WALL ( 4.16 usr +  0.00 sys =  4.16 CPU) @ 2450752.61/s (n=10203559)
                    Rate enc-varint-rec enc-varint-imp
enc-varint-rec 2450753/s             --           -34%
enc-varint-imp 3692143/s            51%             --
```

with optimized loops for varint encoding/decoding.

**Comment by mransan** [comment]
Looks good. Thanks a lot for doing this. Would it be possible to add a unit-test for varint encoding/decoding.

**Comment by c-cube** [comment]
I'll add some test(s). Are there already unit tests? Are we open to introducing some property based testing (qcheck), as a test-only dep?

**Comment by c-cube** [comment]
There's some basic unit tests now, following the existing ones (ish)

**Comment by mransan** [comment]
Looks good. Yes test only dependencies are fine!

**Pull request merged**
