### PR TITLE
Fix 179

### PR DESCRIPTION
**Pull request by c-cube**
cc @pmonson711 , please try this :)

### CODE REVIEW

**Comment by c-cube** [comment]
my bad, didn't see #180

**Comment by pmonson711** [comment]
> my bad, didn't see #180

I've got no attachment to my PR, and the tests look cleaner here. I'll close my PR.

**Comment by pmonson711** [comment]
Also forgot to mention that testing with a local pin did indeed fix the parsing of the EventStore proto file

**Comment by c-cube** [comment]
Thank you! :)

**Pull request merged**
